# Generated by Django 3.2.4 on 2023-05-23 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_alter_newspaper_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspaper',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='redactor',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['id']},
        ),
    ]
